# ...existing code...
INSTALLED_APPS = [
    # ...existing code...
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',  # This must be present
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "hello",
]
# ...existing code...
ROOT_URLCONF = "helloworld.urls"
# ...existing code...
ALLOWED_HOSTS = ["*"]
# ...existing code...
