# ...existing code...
INSTALLED_APPS = [
    # ...existing code...
    "django.contrib.staticfiles",
    "hello",
]
# ...existing code...
ROOT_URLCONF = "helloworld.urls"
# ...existing code...
ALLOWED_HOSTS = ["*"]
# ...existing code...
